### ISSUE TITLE
Error in data generator

### ISSUE THREAD

**Issue by happypanda5** [satvik-venkatesh/data-gen-keras#1]
Hi @satvik-venkatesh . First of all thank you for your blog post. You explain keras datagenerator in a very intuitive manner.

However when I ran the google colab notebook, I got the following error. Is the running fine at your end?

`model.fit(training_generator, validation_data=validation_generator, epochs=5)

InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[25664,2] labels_size=[32,2]
	 [[node categorical_crossentropy/softmax_cross_entropy_with_logits (defined at <ipython-input-12-348c727cd531>:1) ]] [Op:__inference_train_function_5842]

Function call stack:
train_function`

**Comment by satvik-venkatesh** [comment]
Hi @happypanda5 . Thank you for your feedback and pointing out this error. I have fixed the output shapes of the network and the data generator. Kindly check :)
